version: '2'
services:  
  
  asciidoc-html:
    image: asciidoctor/docker-asciidoctor
    volumes:
     - ./samples:/documents/
    command: asciidoctor -a toc -a data-uri -a icons -D /documents/output *.adoc

  asciidoc-pdf:
    image: asciidoctor/docker-asciidoctor
    volumes:
     - ./samples:/documents/
    command: asciidoctor-pdf -a icons -D /documents/output *.adoc

  asciidoc-serve:
    image: nginx
    ports:
     - "8010:80"
    volumes:
     - ./samples/output:/usr/share/nginx/html
  