version: '2'
services:  
  
  # These will start and die
  asciidoc-build:
    image: asciidoctor/docker-asciidoctor
    volumes:
     - ./build.sh:/build.sh
     - ./samples:/documents/
     - ./samples-rendered:/documents-rendered/
    command: bash /build.sh 
    environment:
     - CONFLUENCE_SPACEKEY=${CONFLUENCE_SPACEKEY}
     - CONFLUENCE_TITLE=${CONFLUENCE_TITLE}
     - CONFLUENCE_USERNAME=${CONFLUENCE_USERNAME}
     - CONFLUENCE_PASSWORD=${CONFLUENCE_PASSWORD}

  # # These will stay up and running
  # postgres:
  #   image: postgres
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   environment:
  #     - 'POSTGRES_USER=confluencedb'
  #     - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
  #     - 'POSTGRES_DB=confluencedb'
  #     - 'POSTGRES_ENCODING=UTF8'
  #     - 'POSTGRES_COLLATE=C'
  #     - 'POSTGRES_COLLATE_TYPE=C'
    
  # confluence:
  #   image: atlassian/confluence-server
  #   depends_on:
  #     - postgres
  #   volumes:
  #    - confluence:/var/atlassian/application-data/confluence
  #    - confluence-shared:/var/atlassian/application-data/confluence-shared
  #   ports:
  #    - "8090:8090"
  #    - "8091:8091"

  asciidoc-serve:
    image: nginx
    ports:
     - "8010:80"
    volumes:
     - ./default-site.conf:/etc/nginx/conf.d/default.conf
     - ./samples-rendered:/usr/share/nginx/html
  
# volumes:
#   postgres:
#   confluence:
#   confluence-shared: