version: '2'
services:  
  
  # These will start and die
  asciidoc-build:
    image: asciidoctor/docker-asciidoctor
    volumes:
     - ./build.sh:/build.sh
     - ./samples:/documents/
     - ./data/samples-rendered:/documents-rendered/
    command: bash /build.sh 

  # These will stay up and running
  postgres:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=confluencedb'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=confluencedb'
      - 'POSTGRES_ENCODING=UTF8'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    
  confluence:
    image: atlassian/confluence-server
    depends_on:
      - postgres
    volumes:
     - ./data/confluence:/var/atlassian/application-data/confluence
     - ./data/confluence-shared:/var/atlassian/application-data/confluence-shared
    ports:
     - "8090:8090"
     - "8091:8091"

  # asciidoc-mvn-confluence:
  #   image: maven:3.5-jdk-8
  #   volumes:
  #     - ./data:/root
  #     - ./data/maven-doc:/data/maven-doc
  #     - ./samples:/documents/
  #     - ./build-confluence.sh:/build-confluence.sh
  #   command: bash /build-confluence.sh
  #   environment:
  #    - CONFLUENCE_SPACEKEY=${CONFLUENCE_SPACEKEY}
  #    - CONFLUENCE_ANCESTORID=${CONFLUENCE_ANCESTORID}
  #    - CONFLUENCE_USERNAME=${CONFLUENCE_USERNAME}
  #    - CONFLUENCE_PASSWORD=${CONFLUENCE_PASSWORD}

  asciidoc-serve:
    image: nginx
    ports:
     - "8010:80"
    volumes:
     - ./default-site.conf:/etc/nginx/conf.d/default.conf
     - ./data/samples-rendered:/usr/share/nginx/html
  